# Generated by Django 4.2.2 on 2023-08-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_man', '0002_user_is_active_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
