# Generated by Django 4.2.2 on 2023-08-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_man', '0006_delete_userotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=250)),
                ('task_date', models.DateField()),
                ('task_time', models.TimeField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
