# Generated by Django 4.2.2 on 2023-10-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_man', '0008_task_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
    ]
