# Generated by Django 5.0.1 on 2024-01-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_man', '0009_rename_user_id_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
