# Generated by Django 5.0.1 on 2024-02-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_man', '0011_rename_task_date_task_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='name',
        ),
    ]
